[build]
  publish   = "dist"
  functions = "src/netlify/functions"

[[redirects]]
  from   = "/socket.io/*"
  to     = "/.netlify/functions/socket"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
  force  = true
