# railway.toml - Railway 배포 설정

[build]
# 빌드 명령어
builder = "NIXPACKS"

[deploy]
# 시작 명령어 - 서버 직접 실행
startCommand = "node server/index.js"

# 헬스체크 경로
healthcheckPath = "/api/health"

# 환경 변수
[env]
NODE_ENV = "production"

# 재시작 정책
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3