# railway.toml - Railway 배포 설정 (SPA 라우팅 문제 해결)

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# 환경 변수
[env]
NODE_ENV = "production"

# 재시작 정책
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# 서비스 설정 추가
[deploy.service]
# 포트 설정 (Railway가 자동으로 PORT 환경변수 제공)
port = "$PORT"

# Nixpacks 설정 (빌드 과정 최적화)
[build.nixpacksConfig]
# Node.js 버전 명시
nodeVersion = "18"