
# railway.toml - Railway 배포 설정

[build]
# 빌드 명령어
builder = "NIXPACKS"

[deploy]
# 시작 명령어
startCommand = "node server/index.js"

# 포트 설정 (Railway가 자동으로 할당)
# PORT 환경변수 사용

# 헬스체크 경로
healthcheckPath = "/api/health"

# 환경 변수
[env]
NODE_ENV = "production"

# 재시작 정책
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3