# railway.toml - Railway 배포 설정 (SPA 라우팅 문제 해결)

[build]
# 빌드 명령어 - 프론트엔드 빌드 후 서버 디렉토리로 복사
builder = "NIXPACKS"

[deploy]
# 시작 명령어 - 서버 직접 실행
startCommand = "node server/index.js"

# 헬스체크 경로 (수정됨)
healthcheckPath = "/api/health"
healthcheckTimeout = 300

# 환경 변수
[env]
NODE_ENV = "production"

# 재시작 정책
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# 서비스 설정 추가
[deploy.service]
# 포트 설정 (Railway가 자동으로 PORT 환경변수 제공)
port = "$PORT"

# Nixpacks 설정 (빌드 과정 최적화)
[build.nixpacksConfig]
# Node.js 버전 명시
nodeVersion = "18"