
# railway.toml - Railway 배포 설정

[build]
# 빌드 명령어
builder = "NIXPACKS"

[deploy]
# 시작 명령어 - 빌드된 파일을 복사하고 서버 시작
startCommand = "npm run start"

# 헬스체크 경로
healthcheckPath = "/api/health"

# 환경 변수
[env]
NODE_ENV = "production"

# 재시작 정책
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3