# railway.toml - Railway 배포 설정 개선

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# 환경 변수
[env]
NODE_ENV = "production"

# Nixpacks 설정
[build.nixpacksConfig]
# Node.js 버전 명시
nodeVersion = "18"